spring:
  # DB ??
  datasource:
    # ??? H2 DB? ?? URL
    url: jdbc:h2:tcp://localhost/~/test
    # ??? ?? ????
    driver-class-name: org.h2.Driver
    # springboot 2.4 ??? username? ? ??????. ??? ??? ?????.
    username: sa
  jpa:
    # JPA? ???? SQL? ? ? ??.
    show-sql: true
    # ??? ?? ???? ??? ?? ??. ?? - create, ??? - none
    # ????? ??? create? ????
    # ???? none ?? ???. create?? ??? ???? ?? ??????.
    hibernate:
      ddl-auto: create
  # ?? ?? ? ?? always
  output:
    ansi:
      enabled: always
# ???? ??? ?? trace
logging:
  level:
    org.hibernate.type: trace